name: E2E Test

on: 
  push:
    branches:
      - master
      - releases/**
  pull_request:
    branches:
      - master
      - releases/**

jobs:
  test:
    name: E2E Test on ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node: [16]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run pack

    - name: Test
      id: test
      uses: ./
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        labels: l10n
        state: open

    - name: Check issue count
      run: echo '${{ steps.test.outputs.count }}'
