name: Release

on:
  pull_request:
    types:
      - closed

jobs:
  release:
    name: Release
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          registry-url: "https://registry.npmjs.org"
      - run: git switch master
      - run: npm install
      - run: npm run release:trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}